#ifndef COLOR_H
#define COLOR_H

namespace Color {
    enum Color {
        WHITE = 0x30,
        BLACK = 0x0F,
        GRAY = 0x00,
        GRAY_DARK = 0x2D,
        GRAY_LIGHT = 0x3D,
        GRAY_LIGHTEST = 0x10,
        BLUE = 0x11,
        BLUE_DARK = 0x12,
        BLUE_DARKER = 0x02,
        BLUE_DARKEST = 0x01,
        BLUE_LIGHT = 0x22,
        BLUE_LIGHTER = 0x21,
        BLUE_LIGHTEST = 0x31,
        BLUE_LIGHTEST_PURPLE = 0x32,
        BROWN = 0x07,
        BROWN_LIGHT = 0x17,
        PURPLE = 0x13,
        PURPLE_DARK = 0x03,
        PURPLE_LIGHT = 0x23,
        PURPLE_LIGHTEST = 0x33,
        MAGENTA = 0x14,
        MAGENTA_DARK = 0x04,
        MAGENTA_LIGHT = 0x24,
        MAGENTA_LIGHTEST = 0x34,
        RED = 0x16,
        RED_DARK = 0x06,
        RED_LIGHT = 0x26,
        RED_LIGHTEST = 0x36,
        PINK = 0x25,
        PINK_DARK = 0x15,
        PINK_DARKEST = 0x05,
        PINK_LIGHT = 0x35,
        ORANGE = 0x27,
        ORANGE_LIGHT = 0x37,
        OLIVE = 0x18,
        OLIVE_DARK = 0x08,
        GREEN = 0x1A,
        GREEN_DARK = 0x19,
        GREEN_DARKER = 0x0A,
        GREEN_DARKEST = 0x09,
        GREEN_LIGHT = 0x29,
        GREEN_LIGHTER = 0x2A,
        GREEN_LIGHTEST = 0x3A,
        GREEN_LIGHTEST_YELLOW = 0x39,
        TURQUOISE = 0x1B,
        TURQUOISE_DARK = 0x0B,
        TURQUOISE_LIGHT = 0x2B,
        TURQUOISE_LIGHTEST = 0x3B,
        AQUAMARINE = 0x1C,
        AQUAMARINE_DARK = 0x0C,
        AQUAMARINE_LIGHT = 0x2C,
        AQUAMARINE_LIGHTEST = 0x3C,
        YELLOW = 0x28,
        YELLOW_LIGHT = 0x38
    };
}

#endif // COLOR_H
