#ifndef BRICK_H
#define BRICK_H

namespace Brick {
    enum Brick {
        NO_BRICKS,
        SURFACE,
        SURFACE_AND_CEILING,
        SURFACE_AND_CEILING_3,
        SURFACE_AND_CEILING_4,
        SURFACE_AND_CEILING_8,
        SURFACE_4_AND_CEILING,
        SURFACE_4_AND_CEILING_3,
        SURFACE_4_AND_CEILING_4,
        SURFACE_5_AND_CEILING,
        CEILING,
        SURFACE_5_AND_CEILING_4,
        SURFACE_8_AND_CEILING,
        SURFACE_AND_CEILING_AND_MIDDLE_5,
        SURFACE_AND_CEILING_AND_MIDDLE_4,
        ALL
    };
}

#endif // BRICK_H
